# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mxfun',
                'doc_host': 'https://mone27.github.io',
                'git_url': 'https://github.com/mone27/mxfun-py',
                'lib_path': 'mxfun'},
  'syms': { 'mxfun.core': { 'mxfun.core.L.pipe': ('core.html#l.pipe', 'mxfun/core.py'),
                            'mxfun.core.L.progress_map': ('core.html#l.progress_map', 'mxfun/core.py'),
                            'mxfun.core.Path.add_suffix': ('core.html#path.add_suffix', 'mxfun/core.py'),
                            'mxfun.core.download_file': ('core.html#download_file', 'mxfun/core.py'),
                            'mxfun.core.download_files': ('core.html#download_files', 'mxfun/core.py'),
                            'mxfun.core.file_bbox': ('core.html#file_bbox', 'mxfun/core.py'),
                            'mxfun.core.iter_row_df': ('core.html#iter_row_df', 'mxfun/core.py'),
                            'mxfun.core.str_here': ('core.html#str_here', 'mxfun/core.py'),
                            'mxfun.core.write_bbox_tileindex_dir': ('core.html#write_bbox_tileindex_dir', 'mxfun/core.py')}}}
